version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: quests-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quests
      TZ: Europe/Kyiv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quests-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: quests-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: Europe/Kyiv
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - quests-net

volumes:
  postgres_data:

networks:
  quests-net:
